language: node_js
node_js:
- stable
before_script:
- npm i
- npm run static
deploy:
  local_dir: static
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  - secure: 5exKlMh5ajYuPIhmVJznlamVHMlQOOlzYicYaDsFXzZQm2ZLORrkfYJMyKu3x4ilGm8yfrkwQNjMmhu19Lbp47MoaEfByQpAmphU5o9MJkio0W6rfLvxaEmElt/XaUIEMahrjR6CK7SwfZaTkz41xXryEo/6a5LnaimiYJakdCIRdhJuTWWuixEoAQ8jAgzlVAyzYL1Y8R4Rj7z899h3/nHXeX7SaaYeKfsIT99wi2E74gCJxgU0TYzeUyuy4DMhRTJKTnqxD+mNfAcZ56nYxYvluF+kvfS6ujsTmrUHsZ5x9Yh/Hu6kOd8C32NEszTUtu+vYQ4gsdAGNlK1Vt4GP3uDyPk5xof7hOnUjLzdZ658Gx1peQRU5B8uCdm3WEn2I7GRjDN57sywBLSLaAjMZqA1TkC7Gm2zZQ050qCr70LOw97PuobEoiOH3yuR0nOChNrPUpVHROe/kfuqFe7uRZXRF6Oq+JpSN+ogLaypnIeG/IIbTHw5B/AlrdU25YGesOjrbvMNHN6kxxSxFjLGslYbDioE4gtJEQ7GQtfAwkGkI/DF1KHo1Vg1mXClZpujzTkQSE1F0RLbdHvKz2W05Zd8rFJPZhuU+trLe032ANtKEvGyPh6O9VR4fmJP09cUIOPJvET8CRHzAhOWRzCOhdDq9ZeLqvgq9Y0fgGDb8AU=
